import type { Action } from './types'
import { ACTION_OUTCOMES } from './action-outcomes'

// ─── Action Data (D-01) ─────────────────────────────────────────────────────
// Auto-generated from refs/pf2e/actions/ (545 entries).
// Combat-relevant outcomes merged from ACTION_OUTCOMES.
// DO NOT EDIT BY HAND — regenerate from refs/ data.

const RAW_ACTIONS: Omit<Action, 'outcomes'>[] = [
  { slug: 'a-challenge-for-heroes', name: 'A Challenge for Heroes', actionType: 'action', cost: 2, category: 'offensive', traits: ['concentrate', 'mental', 'spirit', 'transcendence'] },
  { slug: 'a-moment-unending', name: 'A Moment Unending', actionType: 'action', cost: 1, category: null, traits: ['concentrate', 'prediction', 'transcendence'] },
  { slug: 'a-quick-glimpse-beyond', name: 'A Quick Glimpse Beyond', actionType: 'free', cost: null, category: 'offensive', traits: ['fortune'] },
  { slug: 'absorb-into-the-aegis', name: 'Absorb into the Aegis', actionType: 'reaction', cost: null, category: 'defensive', traits: [] },
  { slug: 'accept-echo', name: 'Accept Echo', actionType: 'action', cost: 1, category: 'offensive', traits: ['concentrate', 'occult'] },
  { slug: 'accidental-shot', name: 'Accidental Shot', actionType: 'action', cost: 2, category: 'offensive', traits: ['fortune'] },
  { slug: 'acrid-barrage', name: 'Acrid Barrage', actionType: 'action', cost: 2, category: 'offensive', traits: [] },
  { slug: 'act-together', name: 'Act Together', actionType: 'action', cost: 1, category: 'interaction', traits: ['summoner', 'tandem'] },
  { slug: 'activate-resonant-reflection', name: 'Activate Resonant Reflection', actionType: 'action', cost: 2, category: 'interaction', traits: ['magical'] },
  { slug: 'administer-ambient-magic', name: 'Administer Ambient Magic', actionType: 'action', cost: 1, category: 'defensive', traits: ['healing'] },
  { slug: 'administer-first-aid', name: 'Administer First Aid', actionType: 'action', cost: 2, category: null, traits: ['manipulate'] },
  { slug: 'aegis-of-envy', name: 'Aegis of Envy', actionType: 'action', cost: 2, category: 'offensive', traits: ['arcane', 'concentrate'] },
  { slug: 'affix-a-fulu', name: 'Affix a Fulu', actionType: 'action', cost: 1, category: 'interaction', traits: ['manipulate'] },
  { slug: 'affix-a-talisman', name: 'Affix a Talisman', actionType: 'passive', cost: null, category: null, traits: ['exploration', 'manipulate'] },
  { slug: 'aid', name: 'Aid', actionType: 'reaction', cost: null, category: null, traits: [] },
  { slug: 'alley-oop', name: 'Alley-Oop', actionType: 'action', cost: 1, category: 'offensive', traits: ['commander', 'tactic'] },
  { slug: 'amassed-assault', name: 'Amassed Assault', actionType: 'action', cost: 1, category: 'offensive', traits: ['attack'] },
  { slug: 'amulets-abeyance', name: 'Amulet\'s Abeyance', actionType: 'reaction', cost: null, category: 'defensive', traits: ['magical', 'manipulate', 'thaumaturge'] },
  { slug: 'anadi-venom', name: 'Anadi Venom', actionType: 'action', cost: 1, category: 'offensive', traits: ['anadi'] },
  { slug: 'anchor', name: 'Anchor', actionType: 'action', cost: 1, category: 'offensive', traits: ['leshy'] },
  { slug: 'arcane-cascade', name: 'Arcane Cascade', actionType: 'action', cost: 1, category: 'offensive', traits: ['concentrate', 'magus', 'stance'] },
  { slug: 'armor-up', name: 'Armor Up!', actionType: 'action', cost: 1, category: 'interaction', traits: ['manipulate'] },
  { slug: 'arrest-a-fall', name: 'Arrest a Fall', actionType: 'reaction', cost: null, category: null, traits: [] },
  { slug: 'arrow-splits-arrow', name: 'Arrow Splits Arrow', actionType: 'action', cost: 1, category: 'offensive', traits: ['transcendence'] },
  { slug: 'assume-a-role', name: 'Assume a Role', actionType: 'passive', cost: null, category: 'interaction', traits: ['concentrate', 'exploration'] },
  { slug: 'automaton-aim', name: 'Automaton Aim', actionType: 'action', cost: 1, category: 'offensive', traits: [] },
  { slug: 'avert-gaze', name: 'Avert Gaze', actionType: 'action', cost: 1, category: null, traits: [] },
  { slug: 'avoid-dire-fate', name: 'Avoid Dire Fate', actionType: 'reaction', cost: null, category: 'offensive', traits: ['fortune'] },
  { slug: 'avoid-notice', name: 'Avoid Notice', actionType: 'passive', cost: null, category: 'defensive', traits: ['exploration'] },
  { slug: 'balance', name: 'Balance', actionType: 'action', cost: 1, category: null, traits: ['move'] },
  { slug: 'banshee-cry', name: 'Banshee Cry', actionType: 'reaction', cost: null, category: 'offensive', traits: [] },
  { slug: 'barbed-quills', name: 'Barbed Quills', actionType: 'reaction', cost: null, category: 'offensive', traits: ['shisk'] },
  { slug: 'base-kinesis', name: 'Base Kinesis', actionType: 'action', cost: 2, category: 'interaction', traits: ['impulse', 'kineticist', 'primal'] },
  { slug: 'basic-finisher', name: 'Basic Finisher', actionType: 'action', cost: 1, category: 'offensive', traits: ['finisher'] },
  { slug: 'bear-allies-burdens', name: 'Bear Allies\' Burdens', actionType: 'action', cost: 2, category: 'offensive', traits: ['transcendence'] },
  { slug: 'beasts-charge', name: 'Beast\'s Charge', actionType: 'action', cost: 2, category: 'offensive', traits: ['eidolon'] },
  { slug: 'bend-time', name: 'Bend Time', actionType: 'free', cost: null, category: 'interaction', traits: ['occult'] },
  { slug: 'bestial-clarity', name: 'Bestial Clarity', actionType: 'reaction', cost: null, category: 'offensive', traits: [] },
  { slug: 'binding-vow', name: 'Binding Vow', actionType: 'action', cost: 1, category: 'offensive', traits: ['auditory', 'concentrate', 'occult'] },
  { slug: 'bite-and-sting', name: 'Bite and Sting', actionType: 'action', cost: 1, category: null, traits: [] },
  { slug: 'blazing-conflagration', name: 'Blazing Conflagration', actionType: 'action', cost: 3, category: 'offensive', traits: ['fire', 'healing', 'light', 'visual'] },
  { slug: 'bless-ally', name: 'Bless Ally', actionType: 'action', cost: 1, category: 'interaction', traits: ['concentrate', 'divine', 'fortune', 'mythic'] },
  { slug: 'blinding-of-the-needle', name: 'Blinding of the Needle', actionType: 'action', cost: 2, category: 'offensive', traits: ['transcendence'] },
  { slug: 'blizzard-evasion', name: 'Blizzard Evasion', actionType: 'reaction', cost: null, category: 'defensive', traits: [] },
  { slug: 'bloody-guillotine', name: 'Bloody Guillotine', actionType: 'action', cost: 2, category: 'offensive', traits: ['commander', 'tactic'] },
  { slug: 'board', name: 'Board', actionType: 'action', cost: 1, category: 'interaction', traits: ['move'] },
  { slug: 'boarding-assault', name: 'Boarding Assault', actionType: 'action', cost: 2, category: 'offensive', traits: ['flourish'] },
  { slug: 'bond-with-spirit', name: 'Bond with Spirit', actionType: 'passive', cost: null, category: null, traits: ['concentrate', 'exploration'] },
  { slug: 'borrow-an-arcane-spell', name: 'Borrow an Arcane Spell', actionType: 'passive', cost: null, category: null, traits: ['concentrate', 'exploration'] },
  { slug: 'bounce-away', name: 'Bounce Away', actionType: 'reaction', cost: null, category: 'defensive', traits: [] },
  { slug: 'brandish-the-gorgons-gaze', name: 'Brandish the Gorgon\'s Gaze', actionType: 'action', cost: 1, category: 'offensive', traits: ['earth', 'transcendence', 'visual'] },
  { slug: 'break-free', name: 'Break Free', actionType: 'action', cost: 2, category: 'offensive', traits: ['transcendence'] },
  { slug: 'break-the-suns-legs', name: 'Break the Sun\'s Legs', actionType: 'action', cost: 2, category: 'offensive', traits: ['cold', 'concentrate', 'darkness', 'transcendence'] },
  { slug: 'break-them-down', name: 'Break Them Down', actionType: 'action', cost: 2, category: 'offensive', traits: ['gunslinger'] },
  { slug: 'breath-weapon', name: 'Breath Weapon', actionType: 'action', cost: 2, category: 'offensive', traits: ['arcane', 'eidolon'] },
  { slug: 'bribe-contact', name: 'Bribe Contact', actionType: 'passive', cost: null, category: 'interaction', traits: ['downtime', 'secret'] },
  { slug: 'buckle-cut-blitz', name: 'Buckle-Cut Blitz', actionType: 'action', cost: 2, category: 'offensive', traits: ['brandish', 'commander', 'tactic'] },
  { slug: 'bullet-dancer-stance', name: 'Bullet Dancer Stance', actionType: 'action', cost: 1, category: 'offensive', traits: ['stance'] },
  { slug: 'bullying-press', name: 'Bullying Press', actionType: 'reaction', cost: null, category: 'offensive', traits: ['flourish'] },
  { slug: 'burn-out-of-time', name: 'Burn out of Time', actionType: 'action', cost: 2, category: 'offensive', traits: ['spirit', 'transcendence', 'void'] },
  { slug: 'burrow', name: 'Burrow', actionType: 'action', cost: 1, category: null, traits: ['move'] },
  { slug: 'calculate-threats', name: 'Calculate Threats', actionType: 'action', cost: 1, category: 'defensive', traits: ['mental', 'psyche', 'psychic'] },
  { slug: 'call-companion', name: 'Call Companion', actionType: 'passive', cost: null, category: 'interaction', traits: ['exploration'] },
  { slug: 'call-follower', name: 'Call Follower', actionType: 'passive', cost: null, category: 'offensive', traits: ['exploration'] },
  { slug: 'call-gun', name: 'Call Gun', actionType: 'action', cost: 1, category: 'interaction', traits: ['magical'] },
  { slug: 'call-on-ancient-blood', name: 'Call on Ancient Blood', actionType: 'reaction', cost: null, category: 'defensive', traits: [] },
  { slug: 'call-to-axis', name: 'Call to Axis', actionType: 'free', cost: null, category: 'interaction', traits: ['fortune'] },
  { slug: 'call-to-hand', name: 'Call to Hand', actionType: 'action', cost: 1, category: 'offensive', traits: ['arcane', 'manipulate', 'teleportation'] },
  { slug: 'call-upon-the-brightness', name: 'Call Upon the Brightness', actionType: 'reaction', cost: null, category: 'defensive', traits: ['concentrate'] },
  { slug: 'call-warshard-weapon', name: 'Call Warshard Weapon', actionType: 'action', cost: 1, category: 'offensive', traits: ['magical', 'manipulate', 'teleportation'] },
  { slug: 'captivating-charm', name: 'Captivating Charm', actionType: 'action', cost: 2, category: 'offensive', traits: ['concentrate', 'emotion', 'mental', 'transcendence', 'visual'] },
  { slug: 'cast-a-spell', name: 'Cast a Spell', actionType: 'passive', cost: null, category: 'interaction', traits: [] },
  { slug: 'catharsis', name: 'Catharsis', actionType: 'reaction', cost: null, category: null, traits: ['concentrate', 'emotion', 'mental'] },
  { slug: 'change-shape', name: 'Change Shape', actionType: 'action', cost: 1, category: 'interaction', traits: ['concentrate', 'polymorph'] },
  { slug: 'change-tradition-focus', name: 'Change Tradition Focus', actionType: 'action', cost: 1, category: 'interaction', traits: [] },
  { slug: 'channel-draconic-essence', name: 'Channel Draconic Essence', actionType: 'action', cost: 1, category: 'offensive', traits: ['concentrate'] },
  { slug: 'channel-elements', name: 'Channel Elements', actionType: 'action', cost: 1, category: 'offensive', traits: ['aura', 'kineticist', 'primal'] },
  { slug: 'chaotic-destiny', name: 'Chaotic Destiny', actionType: 'free', cost: null, category: 'offensive', traits: ['fortune'] },
  { slug: 'chassis-deflection', name: 'Chassis Deflection', actionType: 'reaction', cost: null, category: 'defensive', traits: ['automaton'] },
  { slug: 'claw-stance', name: 'Claw Stance', actionType: 'action', cost: 1, category: 'offensive', traits: ['stance'] },
  { slug: 'cleanse-soul-path', name: 'Cleanse Soul Path', actionType: 'passive', cost: null, category: 'interaction', traits: ['exploration'] },
  { slug: 'clear-a-path', name: 'Clear a Path', actionType: 'action', cost: 1, category: 'offensive', traits: ['gunslinger'] },
  { slug: 'climb', name: 'Climb', actionType: 'action', cost: 1, category: 'interaction', traits: ['move'] },
  { slug: 'clue-in', name: 'Clue In', actionType: 'reaction', cost: null, category: 'interaction', traits: ['concentrate', 'investigator'] },
  { slug: 'cobble-together', name: 'Cobble Together', actionType: 'passive', cost: null, category: 'interaction', traits: ['exploration'] },
  { slug: 'coerce', name: 'Coerce', actionType: 'passive', cost: null, category: 'interaction', traits: ['auditory', 'concentrate', 'emotion', 'exploration', 'linguistic', 'mental'] },
  { slug: 'coiling-serpents', name: 'Coiling Serpents', actionType: 'action', cost: 2, category: 'offensive', traits: [] },
  { slug: 'collect-spirit-remnant', name: 'Collect Spirit Remnant', actionType: 'action', cost: 3, category: 'interaction', traits: ['concentrate', 'manipulate'] },
  { slug: 'command-a-construct', name: 'Command a Construct', actionType: 'action', cost: 1, category: 'interaction', traits: ['auditory', 'concentrate'] },
  { slug: 'command-an-animal', name: 'Command an Animal', actionType: 'action', cost: 1, category: 'interaction', traits: ['auditory', 'concentrate'] },
  { slug: 'compose-missive', name: 'Compose Missive', actionType: 'passive', cost: null, category: 'interaction', traits: ['exploration', 'manipulate'] },
  { slug: 'conceal-an-object', name: 'Conceal an Object', actionType: 'action', cost: 1, category: 'interaction', traits: ['manipulate', 'secret'] },
  { slug: 'conduct-energy', name: 'Conduct Energy', actionType: 'free', cost: null, category: 'interaction', traits: [] },
  { slug: 'confident-finisher', name: 'Confident Finisher', actionType: 'action', cost: 1, category: 'offensive', traits: ['finisher'] },
  { slug: 'conjure-bullet', name: 'Conjure Bullet', actionType: 'action', cost: 1, category: 'interaction', traits: ['magical'] },
  { slug: 'consume-flesh', name: 'Consume Flesh', actionType: 'action', cost: 1, category: 'interaction', traits: ['manipulate'] },
  { slug: 'convocation-of-greed', name: 'Convocation of Greed', actionType: 'action', cost: 2, category: 'offensive', traits: ['arcane', 'concentrate'] },
  { slug: 'coordinating-maneuvers', name: 'Coordinating Maneuvers', actionType: 'action', cost: 1, category: 'offensive', traits: ['brandish', 'commander', 'tactic'] },
  { slug: 'coughing-dragon', name: 'Coughing Dragon', actionType: 'action', cost: 2, category: 'offensive', traits: [] },
  { slug: 'cover-tracks', name: 'Cover Tracks', actionType: 'passive', cost: null, category: 'defensive', traits: ['concentrate', 'exploration', 'move'] },
  { slug: 'covered-reload', name: 'Covered Reload', actionType: 'action', cost: 1, category: 'offensive', traits: ['gunslinger'] },
  { slug: 'craft', name: 'Craft', actionType: 'passive', cost: null, category: 'interaction', traits: ['downtime', 'manipulate'] },
  { slug: 'craft-disharmonic-instrument', name: 'Craft Disharmonic Instrument', actionType: 'passive', cost: null, category: 'interaction', traits: ['downtime', 'manipulate'] },
  { slug: 'cram', name: 'Cram', actionType: 'passive', cost: null, category: 'interaction', traits: ['downtime'] },
  { slug: 'crash-against-me', name: 'Crash Against Me', actionType: 'action', cost: 1, category: 'offensive', traits: ['transcendence'] },
  { slug: 'crawl', name: 'Crawl', actionType: 'action', cost: 1, category: 'defensive', traits: ['move'] },
  { slug: 'create-a-diversion', name: 'Create a Diversion', actionType: 'action', cost: 1, category: 'interaction', traits: ['mental'] },
  { slug: 'create-familiar-fulu', name: 'Create Familiar Fulu', actionType: 'action', cost: 2, category: 'interaction', traits: ['concentrate', 'manipulate'] },
  { slug: 'create-forgery', name: 'Create Forgery', actionType: 'passive', cost: null, category: 'interaction', traits: ['downtime', 'secret'] },
  { slug: 'crescent-spray', name: 'Crescent Spray', actionType: 'action', cost: 2, category: 'offensive', traits: ['flourish'] },
  { slug: 'cry-havoc', name: 'Cry Havoc!', actionType: 'action', cost: 3, category: 'offensive', traits: ['brandish', 'commander', 'tactic'] },
  { slug: 'cycle-elemental-stance', name: 'Cycle Elemental Stance', actionType: 'action', cost: 1, category: 'interaction', traits: [] },
  { slug: 'dampening-harmonics', name: 'Dampening Harmonics', actionType: 'action', cost: 2, category: 'offensive', traits: ['magical'] },
  { slug: 'dancing-dodge', name: 'Dancing Dodge', actionType: 'reaction', cost: null, category: 'offensive', traits: ['move'] },
  { slug: 'daydream-trance', name: 'Daydream Trance', actionType: 'action', cost: 1, category: 'interaction', traits: ['mental', 'occult'] },
  { slug: 'dazzle-seeker', name: 'Dazzle Seeker', actionType: 'reaction', cost: null, category: 'defensive', traits: ['misfortune'] },
  { slug: 'death-drone', name: 'Death Drone', actionType: 'action', cost: 2, category: 'offensive', traits: ['auditory', 'flourish', 'mental'] },
  { slug: 'debilitating-strike', name: 'Debilitating Strike', actionType: 'free', cost: null, category: 'offensive', traits: ['rogue'] },
  { slug: 'deceptive-sidestep', name: 'Deceptive Sidestep', actionType: 'reaction', cost: null, category: 'defensive', traits: ['misfortune'] },
  { slug: 'decipher-writing', name: 'Decipher Writing', actionType: 'passive', cost: null, category: 'interaction', traits: ['concentrate', 'exploration', 'secret'] },
  { slug: 'decompose', name: 'Decompose', actionType: 'action', cost: 2, category: 'offensive', traits: ['primal', 'void'] },
  { slug: 'deconstruct', name: 'Deconstruct', actionType: 'passive', cost: null, category: 'interaction', traits: ['downtime'] },
  { slug: 'defend', name: 'Defend', actionType: 'passive', cost: null, category: 'defensive', traits: ['exploration'] },
  { slug: 'defend-life', name: 'Defend Life', actionType: 'reaction', cost: null, category: 'interaction', traits: ['concentrate'] },
  { slug: 'defensive-retreat', name: 'Defensive Retreat', actionType: 'action', cost: 2, category: 'offensive', traits: ['brandish', 'commander', 'tactic'] },
  { slug: 'delay', name: 'Delay', actionType: 'free', cost: null, category: 'interaction', traits: [] },
  { slug: 'demoralize', name: 'Demoralize', actionType: 'action', cost: 1, category: 'offensive', traits: ['auditory', 'concentrate', 'emotion', 'fear', 'mental'] },
  { slug: 'demoralizing-charge', name: 'Demoralizing Charge', actionType: 'action', cost: 2, category: 'offensive', traits: ['brandish', 'commander', 'tactic'] },
  { slug: 'designate-ally', name: 'Designate Ally', actionType: 'action', cost: 1, category: 'interaction', traits: [] },
  { slug: 'destructive-vengeance', name: 'Destructive Vengeance', actionType: 'reaction', cost: null, category: 'offensive', traits: ['champion', 'divine'] },
  { slug: 'detect-magic', name: 'Detect Magic', actionType: 'passive', cost: null, category: 'interaction', traits: ['concentrate', 'exploration'] },
  { slug: 'devise-a-stratagem', name: 'Devise a Stratagem', actionType: 'action', cost: 1, category: 'offensive', traits: ['concentrate', 'investigator'] },
  { slug: 'devour-ambient-magic', name: 'Devour Ambient Magic', actionType: 'reaction', cost: null, category: 'defensive', traits: ['concentrate'] },
  { slug: 'direct-follower', name: 'Direct Follower', actionType: 'action', cost: 1, category: 'offensive', traits: ['concentrate'] },
  { slug: 'disable-a-device', name: 'Disable a Device', actionType: 'action', cost: 2, category: 'interaction', traits: ['manipulate'] },
  { slug: 'disarm', name: 'Disarm', actionType: 'action', cost: 1, category: 'offensive', traits: ['attack'] },
  { slug: 'disarming-interception', name: 'Disarming Interception', actionType: 'reaction', cost: null, category: 'defensive', traits: [] },
  { slug: 'discover', name: 'Discover', actionType: 'passive', cost: null, category: 'interaction', traits: ['concentrate', 'secret'] },
  { slug: 'dismiss', name: 'Dismiss', actionType: 'action', cost: 1, category: 'interaction', traits: ['concentrate'] },
  { slug: 'dispelling-bullet', name: 'Dispelling Bullet', actionType: 'action', cost: 2, category: 'offensive', traits: ['magical', 'spellshot'] },
  { slug: 'divert-lightning', name: 'Divert Lightning', actionType: 'reaction', cost: null, category: 'offensive', traits: ['electricity'] },
  { slug: 'double-team', name: 'Double Team', actionType: 'action', cost: 2, category: 'offensive', traits: ['commander', 'tactic'] },
  { slug: 'draconic-frenzy', name: 'Draconic Frenzy', actionType: 'action', cost: 2, category: 'offensive', traits: ['eidolon'] },
  { slug: 'draconic-salvation', name: 'Draconic Salvation', actionType: 'reaction', cost: null, category: 'defensive', traits: ['concentrate', 'fortune'] },
  { slug: 'dragon-breath', name: 'Dragon Breath', actionType: 'action', cost: 2, category: 'offensive', traits: [] },
  { slug: 'dragon-breath-dragon-form', name: 'Dragon Breath (Dragon Form)', actionType: 'action', cost: 2, category: 'offensive', traits: [] },
  { slug: 'dragons-protection', name: 'Dragon\'s Protection', actionType: 'reaction', cost: null, category: 'offensive', traits: ['concentrate', 'sanctified', 'spirit'] },
  { slug: 'drain-bonded-item', name: 'Drain Bonded Item', actionType: 'free', cost: null, category: 'interaction', traits: ['arcane', 'wizard'] },
  { slug: 'drain-life', name: 'Drain Life', actionType: 'action', cost: 2, category: 'offensive', traits: ['divine', 'eidolon', 'void'] },
  { slug: 'drain-realm', name: 'Drain Realm', actionType: 'free', cost: null, category: 'interaction', traits: ['concentrate'] },
  { slug: 'drape-ambient-magic', name: 'Drape Ambient Magic', actionType: 'action', cost: 1, category: 'defensive', traits: ['illusion'] },
  { slug: 'draw-from-the-pages', name: 'Draw From the Pages', actionType: 'action', cost: 3, category: 'offensive', traits: ['manipulate'] },
  { slug: 'drifters-wake', name: 'Drifter\'s Wake', actionType: 'action', cost: 3, category: 'offensive', traits: ['gunslinger'] },
  { slug: 'drink-blood', name: 'Drink Blood', actionType: 'action', cost: 1, category: 'offensive', traits: ['divine'] },
  { slug: 'drink-from-the-chalice', name: 'Drink from the Chalice', actionType: 'action', cost: 1, category: 'defensive', traits: ['magical', 'manipulate', 'thaumaturge'] },
  { slug: 'drink-of-my-foes', name: 'Drink of my Foes', actionType: 'action', cost: 1, category: 'offensive', traits: ['healing', 'transcendence', 'vitality'] },
  { slug: 'drive', name: 'Drive', actionType: 'action', cost: 1, category: 'interaction', traits: ['move'] },
  { slug: 'drop-prone', name: 'Drop Prone', actionType: 'action', cost: 1, category: 'defensive', traits: ['move'] },
  { slug: 'dueling-counter', name: 'Dueling Counter', actionType: 'reaction', cost: null, category: 'defensive', traits: ['magical'] },
  { slug: 'dutiful-retaliation', name: 'Dutiful Retaliation', actionType: 'reaction', cost: null, category: 'offensive', traits: ['eidolon', 'occult'] },
  { slug: 'earn-income', name: 'Earn Income', actionType: 'passive', cost: null, category: 'interaction', traits: ['downtime'] },
  { slug: 'eldritch-shot', name: 'Eldritch Shot', actionType: 'action', cost: 3, category: 'offensive', traits: [] },
  { slug: 'elemental-blast', name: 'Elemental Blast', actionType: 'action', cost: 1, category: 'offensive', traits: ['attack', 'impulse', 'kineticist', 'primal'] },
  { slug: 'elemental-burst', name: 'Elemental Burst', actionType: 'action', cost: 2, category: 'offensive', traits: ['concentrate', 'eidolon'] },
  { slug: 'elemental-maelstrom', name: 'Elemental Maelstrom', actionType: 'action', cost: 3, category: 'offensive', traits: ['eidolon'] },
  { slug: 'embrace-of-destiny', name: 'Embrace of Destiny', actionType: 'action', cost: 1, category: 'offensive', traits: ['mental', 'spirit', 'transcendence'] },
  { slug: 'empty-vessel', name: 'Empty Vessel', actionType: 'reaction', cost: null, category: 'defensive', traits: ['concentrate'] },
  { slug: 'encouraging-words', name: 'Encouraging Words', actionType: 'action', cost: 1, category: 'interaction', traits: ['auditory', 'linguistic', 'mental'] },
  { slug: 'end-it', name: 'End It!', actionType: 'action', cost: 2, category: 'offensive', traits: ['brandish', 'commander', 'incapacitation', 'tactic'] },
  { slug: 'energy-emanation', name: 'Energy Emanation', actionType: 'action', cost: 2, category: 'offensive', traits: ['primal'] },
  { slug: 'energy-shot', name: 'Energy Shot', actionType: 'free', cost: null, category: 'offensive', traits: ['magical', 'spellshot'] },
  { slug: 'engineers-efficiency', name: 'Engineer\'s Efficiency', actionType: 'action', cost: 1, category: 'offensive', traits: [] },
  { slug: 'enlightenment-in-adversity', name: 'Enlightenment in Adversity', actionType: 'reaction', cost: null, category: 'interaction', traits: ['fortune'] },
  { slug: 'enter-runewell', name: 'Enter Runewell', actionType: 'passive', cost: null, category: 'offensive', traits: ['concentrate', 'manipulate', 'teleportation'] },
  { slug: 'enter-seat-of-power', name: 'Enter Seat Of Power', actionType: 'passive', cost: null, category: 'interaction', traits: ['concentrate', 'exploration', 'mythic'] },
  { slug: 'enter-spirit-trance', name: 'Enter Spirit Trance', actionType: 'action', cost: 1, category: 'offensive', traits: ['concentrate', 'divine', 'mental'] },
  { slug: 'entitys-resurgence', name: 'Entity\'s Resurgence', actionType: 'reaction', cost: null, category: 'defensive', traits: [] },
  { slug: 'entreat-pact', name: 'Entreat Pact', actionType: 'free', cost: null, category: 'offensive', traits: ['concentrate', 'fortune'] },
  { slug: 'envenom', name: 'Envenom', actionType: 'action', cost: 1, category: 'offensive', traits: ['manipulate'] },
  { slug: 'erupting-spurs', name: 'Erupting Spurs', actionType: 'reaction', cost: null, category: 'offensive', traits: [] },
  { slug: 'escape', name: 'Escape', actionType: 'action', cost: 1, category: 'interaction', traits: ['attack'] },
  { slug: 'executioners-volley', name: 'Executioner\'s Volley', actionType: 'action', cost: 2, category: 'offensive', traits: ['commander', 'tactic'] },
  { slug: 'expeditious-inspection', name: 'Expeditious Inspection', actionType: 'free', cost: null, category: 'interaction', traits: ['investigator'] },
  { slug: 'expel-maelstrom', name: 'Expel Maelstrom', actionType: 'action', cost: 1, category: null, traits: ['curse', 'occult'] },
  { slug: 'explode', name: 'Explode', actionType: 'action', cost: 2, category: 'interaction', traits: ['fire', 'inventor', 'manipulate', 'unstable'] },
  { slug: 'exploit-vulnerability', name: 'Exploit Vulnerability', actionType: 'action', cost: 1, category: null, traits: ['esoterica', 'manipulate', 'thaumaturge'] },
  { slug: 'extract-element', name: 'Extract Element', actionType: 'action', cost: 1, category: 'offensive', traits: ['impulse', 'kineticist', 'primal'] },
  { slug: 'fade-into-daydreams', name: 'Fade Into Daydreams', actionType: 'action', cost: 1, category: 'defensive', traits: ['illusion', 'psyche', 'psychic'] },
  { slug: 'fated-not-to-die', name: 'Fated Not to Die', actionType: 'free', cost: null, category: 'offensive', traits: ['fortune'] },
  { slug: 'feed-the-masses', name: 'Feed the Masses', actionType: 'action', cost: 1, category: 'offensive', traits: ['transcendence'] },
  { slug: 'feint', name: 'Feint', actionType: 'action', cost: 1, category: 'offensive', traits: ['mental'] },
  { slug: 'feral-swing', name: 'Feral Swing', actionType: 'action', cost: 2, category: 'offensive', traits: ['spirit', 'transcendence'] },
  { slug: 'fey-jump', name: 'Fey Jump', actionType: 'action', cost: 1, category: 'offensive', traits: ['concentrate', 'primal', 'teleportation'] },
  { slug: 'feys-fortune', name: 'Fey\'s Fortune', actionType: 'free', cost: null, category: 'interaction', traits: ['concentrate', 'fortune'] },
  { slug: 'field-of-roots', name: 'Field of Roots', actionType: 'action', cost: 2, category: 'offensive', traits: ['eidolon'] },
  { slug: 'fight-with-fear', name: 'Fight with Fear', actionType: 'reaction', cost: null, category: 'interaction', traits: ['concentrate', 'emotion', 'fear', 'mental'] },
  { slug: 'final-spite', name: 'Final Spite', actionType: 'reaction', cost: null, category: 'defensive', traits: [] },
  { slug: 'final-surge', name: 'Final Surge', actionType: 'action', cost: 1, category: 'offensive', traits: [] },
  { slug: 'find-fault', name: 'Find Fault', actionType: 'reaction', cost: null, category: 'defensive', traits: ['concentrate'] },
  { slug: 'finish-the-job', name: 'Finish The Job', actionType: 'action', cost: 1, category: 'offensive', traits: ['gunslinger'] },
  { slug: 'fire-in-the-hole', name: 'Fire in the Hole', actionType: 'reaction', cost: null, category: 'offensive', traits: [] },
  { slug: 'flash-of-grandeur', name: 'Flash of Grandeur', actionType: 'reaction', cost: null, category: 'defensive', traits: ['champion', 'divine'] },
  { slug: 'flash-of-memory', name: 'Flash of Memory', actionType: 'free', cost: null, category: 'offensive', traits: [] },
  { slug: 'fleeting-arc-through-heaven-and-earth', name: 'Fleeting Arc through Heaven and Earth', actionType: 'action', cost: 3, category: 'offensive', traits: ['light', 'spirit', 'teleportation', 'transcendence'] },
  { slug: 'fling-magic', name: 'Fling Magic', actionType: 'action', cost: 2, category: 'offensive', traits: ['concentrate', 'magical', 'manipulate', 'thaumaturge'] },
  { slug: 'flowing-spirit-strike', name: 'Flowing Spirit Strike', actionType: 'action', cost: 2, category: 'offensive', traits: ['spirit', 'transcendence'] },
  { slug: 'flurry-of-blows', name: 'Flurry of Blows', actionType: 'action', cost: 1, category: 'offensive', traits: ['flourish', 'monk'] },
  { slug: 'fly', name: 'Fly', actionType: 'action', cost: 1, category: 'interaction', traits: ['move'] },
  { slug: 'flyby-attack', name: 'Flyby Attack', actionType: 'action', cost: 2, category: 'offensive', traits: [] },
  { slug: 'follow-the-expert', name: 'Follow the Expert', actionType: 'passive', cost: null, category: 'interaction', traits: ['auditory', 'concentrate', 'exploration', 'visual'] },
  { slug: 'force-open', name: 'Force Open', actionType: 'action', cost: 1, category: 'interaction', traits: ['attack'] },
  { slug: 'forced-pact', name: 'Forced Pact', actionType: 'action', cost: 1, category: 'offensive', traits: ['concentrate'] },
  { slug: 'foresight', name: 'Foresight', actionType: 'reaction', cost: null, category: 'defensive', traits: [] },
  { slug: 'forge-documents', name: 'Forge Documents', actionType: 'passive', cost: null, category: 'interaction', traits: ['downtime', 'secret'] },
  { slug: 'fortify-camp', name: 'Fortify Camp', actionType: 'passive', cost: null, category: 'interaction', traits: [] },
  { slug: 'fortify-focus', name: 'Fortify Focus', actionType: 'action', cost: 2, category: 'interaction', traits: ['concentrate'] },
  { slug: 'fracture-mountains', name: 'Fracture Mountains', actionType: 'action', cost: 2, category: 'offensive', traits: ['spirit', 'transcendence'] },
  { slug: 'furious-strike', name: 'Furious Strike', actionType: 'action', cost: 2, category: 'offensive', traits: ['eidolon'] },
  { slug: 'gain-contact', name: 'Gain Contact', actionType: 'passive', cost: null, category: 'interaction', traits: ['downtime'] },
  { slug: 'gather-information', name: 'Gather Information', actionType: 'passive', cost: null, category: 'interaction', traits: ['exploration', 'secret'] },
  { slug: 'gather-to-me', name: 'Gather to Me!', actionType: 'action', cost: 1, category: 'offensive', traits: ['commander', 'tactic'] },
  { slug: 'ghost-shot', name: 'Ghost Shot', actionType: 'action', cost: 1, category: 'offensive', traits: ['flourish', 'gunslinger'] },
  { slug: 'giant-felling-comet', name: 'Giant-Felling Comet', actionType: 'action', cost: 2, category: 'offensive', traits: ['spirit', 'transcendence'] },
  { slug: 'glimpse-of-redemption', name: 'Glimpse of Redemption', actionType: 'reaction', cost: null, category: 'defensive', traits: ['champion', 'divine'] },
  { slug: 'glimpse-vulnerability', name: 'Glimpse Vulnerability', actionType: 'action', cost: 1, category: null, traits: ['esoterica', 'manipulate'] },
  { slug: 'gluttonous-feast', name: 'Gluttonous Feast', actionType: 'action', cost: 2, category: 'offensive', traits: ['arcane', 'concentrate'] },
  { slug: 'goblin-jubilee', name: 'Goblin Jubilee', actionType: 'action', cost: 3, category: 'offensive', traits: ['fire', 'sonic', 'visual'] },
  { slug: 'gossip', name: 'Gossip', actionType: 'passive', cost: null, category: 'interaction', traits: ['downtime', 'secret'] },
  { slug: 'grab-an-edge', name: 'Grab an Edge', actionType: 'reaction', cost: null, category: 'interaction', traits: ['manipulate'] },
  { slug: 'grapple', name: 'Grapple', actionType: 'action', cost: 1, category: 'interaction', traits: ['attack'] },
  { slug: 'grim-swagger', name: 'Grim Swagger', actionType: 'action', cost: 2, category: 'offensive', traits: ['auditory', 'emotion', 'fear', 'gunslinger', 'linguistic', 'mental'] },
  { slug: 'grow', name: 'Grow', actionType: 'passive', cost: null, category: 'interaction', traits: ['downtime', 'manipulate'] },
  { slug: 'guerrilla-assault', name: 'Guerrilla Assault', actionType: 'action', cost: 1, category: 'offensive', traits: [] },
  { slug: 'harrow-the-fiend', name: 'Harrow the Fiend', actionType: 'free', cost: null, category: 'offensive', traits: ['fortune'] },
  { slug: 'harvest-blood', name: 'Harvest Blood', actionType: 'action', cost: 1, category: 'offensive', traits: [] },
  { slug: 'harvest-heartsliver', name: 'Harvest Heartsliver', actionType: 'reaction', cost: null, category: 'offensive', traits: ['manipulate'] },
  { slug: 'haunting-visage', name: 'Haunting Visage', actionType: 'action', cost: 1, category: 'offensive', traits: ['concentrate', 'eidolon', 'manipulate', 'visual'] },
  { slug: 'heaven-rains-an-ending', name: 'Heaven Rains an Ending', actionType: 'action', cost: 3, category: 'offensive', traits: ['transcendence'] },
  { slug: 'heavy-is-the-crown', name: 'Heavy is the Crown', actionType: 'action', cost: 2, category: 'offensive', traits: ['concentrate', 'mental', 'spirit', 'transcendence'] },
  { slug: 'hellbreaker-strike', name: 'Hellbreaker Strike', actionType: 'action', cost: 2, category: 'offensive', traits: ['holy'] },
  { slug: 'hide', name: 'Hide', actionType: 'action', cost: 1, category: 'interaction', traits: ['secret'] },
  { slug: 'high-jump', name: 'High Jump', actionType: 'action', cost: 2, category: 'interaction', traits: ['move'] },
  { slug: 'host-of-wrath', name: 'Host of Wrath', actionType: 'action', cost: 2, category: 'offensive', traits: ['arcane', 'concentrate'] },
  { slug: 'host-spirit', name: 'Host Spirit', actionType: 'passive', cost: null, category: 'interaction', traits: ['exploration', 'occult'] },
  { slug: 'hunt-prey', name: 'Hunt Prey', actionType: 'action', cost: 1, category: 'offensive', traits: ['concentrate', 'ranger'] },
  { slug: 'hunt-runelord', name: 'Hunt Runelord', actionType: 'action', cost: 1, category: 'offensive', traits: ['concentrate'] },
  { slug: 'hunt-the-razers-pawn', name: 'Hunt the Razer\'s Pawn', actionType: 'action', cost: 1, category: 'offensive', traits: [] },
  { slug: 'hustle', name: 'Hustle', actionType: 'passive', cost: null, category: 'interaction', traits: ['exploration', 'move'] },
  { slug: 'i-defy-you', name: 'I Defy You!', actionType: 'reaction', cost: null, category: 'defensive', traits: ['fortune', 'mental'] },
  { slug: 'identify-alchemy', name: 'Identify Alchemy', actionType: 'passive', cost: null, category: 'interaction', traits: ['concentrate', 'exploration', 'secret'] },
  { slug: 'identify-magic', name: 'Identify Magic', actionType: 'passive', cost: null, category: 'interaction', traits: ['concentrate', 'exploration', 'secret'] },
  { slug: 'impersonate', name: 'Impersonate', actionType: 'passive', cost: null, category: 'interaction', traits: ['concentrate', 'exploration', 'manipulate', 'secret'] },
  { slug: 'implements-interruption', name: 'Implement\'s Interruption', actionType: 'reaction', cost: null, category: 'offensive', traits: ['magical', 'thaumaturge'] },
  { slug: 'impromptu-investment', name: 'Impromptu Investment', actionType: 'passive', cost: null, category: 'offensive', traits: [] },
  { slug: 'indomitable-act', name: 'Indomitable Act', actionType: 'reaction', cost: null, category: 'offensive', traits: [] },
  { slug: 'infiltrators-draw', name: 'Infiltrator\'s Draw', actionType: 'action', cost: 1, category: 'offensive', traits: [] },
  { slug: 'influence', name: 'Influence', actionType: 'passive', cost: null, category: 'interaction', traits: ['concentrate', 'linguistic'] },
  { slug: 'influence-rumor', name: 'Influence Rumor', actionType: 'passive', cost: null, category: 'interaction', traits: ['downtime'] },
  { slug: 'inscribe-shadow-pamor', name: 'Inscribe Shadow Pamor', actionType: 'action', cost: 1, category: 'offensive', traits: ['occult', 'shadow'] },
  { slug: 'inspired-stratagem', name: 'Inspired Stratagem', actionType: 'reaction', cost: null, category: 'offensive', traits: ['fortune', 'linguistic'] },
  { slug: 'insta-ballista', name: 'Insta-Ballista', actionType: 'action', cost: 2, category: 'offensive', traits: ['brandish', 'commander', 'tactic'] },
  { slug: 'instant-recovery', name: 'Instant Recovery', actionType: 'action', cost: 1, category: 'offensive', traits: ['concentrate', 'healing', 'mythic'] },
  { slug: 'intensify-vulnerability', name: 'Intensify Vulnerability', actionType: 'action', cost: 1, category: 'offensive', traits: ['concentrate', 'esoterica', 'magical', 'thaumaturge'] },
  { slug: 'interact', name: 'Interact', actionType: 'action', cost: 1, category: 'interaction', traits: ['manipulate'] },
  { slug: 'intercept-attack', name: 'Intercept Attack', actionType: 'reaction', cost: null, category: 'defensive', traits: ['guardian'] },
  { slug: 'intercession-spell', name: 'Intercession Spell', actionType: 'reaction', cost: null, category: 'defensive', traits: ['concentrate', 'divine', 'spellshape'] },
  { slug: 'into-the-fray', name: 'Into the Fray', actionType: 'free', cost: null, category: 'offensive', traits: ['gunslinger'] },
  { slug: 'inured-to-death', name: 'Inured to Death', actionType: 'reaction', cost: null, category: 'defensive', traits: [] },
  { slug: 'invest-an-item', name: 'Invest an Item', actionType: 'passive', cost: null, category: 'interaction', traits: [] },
  { slug: 'investigate', name: 'Investigate', actionType: 'passive', cost: null, category: 'interaction', traits: ['concentrate', 'exploration'] },
  { slug: 'invigorating-fear', name: 'Invigorating Fear', actionType: 'reaction', cost: null, category: 'interaction', traits: [] },
  { slug: 'invoke-celestial-privilege', name: 'Invoke Celestial Privilege', actionType: 'reaction', cost: null, category: 'defensive', traits: [] },
  { slug: 'iron-command', name: 'Iron Command', actionType: 'reaction', cost: null, category: 'offensive', traits: ['champion', 'divine', 'emotion', 'mental'] },
  { slug: 'jinx', name: 'Jinx', actionType: 'action', cost: 2, category: 'offensive', traits: ['curse', 'occult'] },
  { slug: 'jumping-jenny', name: 'Jumping Jenny', actionType: 'action', cost: 1, category: 'offensive', traits: [] },
  { slug: 'lantern-beam', name: 'Lantern Beam', actionType: 'action', cost: 1, category: 'offensive', traits: ['fire', 'light', 'magical'] },
  { slug: 'lantern-strobe', name: 'Lantern Strobe', actionType: 'action', cost: 2, category: 'offensive', traits: ['light', 'magical', 'visual'] },
  { slug: 'launch-fireworks', name: 'Launch Fireworks', actionType: 'action', cost: 1, category: 'offensive', traits: ['manipulate'] },
  { slug: 'lay-down-arms', name: 'Lay Down Arms', actionType: 'action', cost: 1, category: 'offensive', traits: [] },
  { slug: 'leap', name: 'Leap', actionType: 'action', cost: 1, category: 'interaction', traits: ['move'] },
  { slug: 'learn-a-spell', name: 'Learn a Spell', actionType: 'passive', cost: null, category: 'interaction', traits: ['concentrate', 'exploration'] },
  { slug: 'learn-name', name: 'Learn Name', actionType: 'passive', cost: null, category: 'interaction', traits: ['downtime', 'secret'] },
  { slug: 'liars-hidden-blade', name: 'Liar\'s Hidden Blade', actionType: 'action', cost: 1, category: 'offensive', traits: ['spirit', 'transcendence'] },
  { slug: 'liberating-step', name: 'Liberating Step', actionType: 'reaction', cost: null, category: 'defensive', traits: ['champion'] },
  { slug: 'lie', name: 'Lie', actionType: 'passive', cost: null, category: 'interaction', traits: ['auditory', 'concentrate', 'linguistic', 'mental', 'secret'] },
  { slug: 'life-block', name: 'Life Block', actionType: 'reaction', cost: null, category: 'defensive', traits: [] },
  { slug: 'living-fortification', name: 'Living Fortification', actionType: 'free', cost: null, category: 'offensive', traits: ['gunslinger'] },
  { slug: 'long-jump', name: 'Long Jump', actionType: 'action', cost: 2, category: 'interaction', traits: ['move'] },
  { slug: 'long-term-rest', name: 'Long-Term Rest', actionType: 'passive', cost: null, category: 'interaction', traits: ['downtime'] },
  { slug: 'lucky-break', name: 'Lucky Break', actionType: 'free', cost: null, category: 'offensive', traits: ['fortune'] },
  { slug: 'make-an-impression', name: 'Make an Impression', actionType: 'passive', cost: null, category: 'interaction', traits: ['auditory', 'concentrate', 'exploration', 'linguistic', 'mental'] },
  { slug: 'makes-me-stronger', name: 'Makes Me Stronger', actionType: 'reaction', cost: null, category: 'defensive', traits: [] },
  { slug: 'maneuver-in-flight', name: 'Maneuver in Flight', actionType: 'action', cost: 1, category: 'interaction', traits: ['move'] },
  { slug: 'manifest-eidolon', name: 'Manifest Eidolon', actionType: 'action', cost: 3, category: 'interaction', traits: ['concentrate', 'manipulate', 'summoner', 'teleportation'] },
  { slug: 'manifest-realm', name: 'Manifest Realm', actionType: 'action', cost: 2, category: 'offensive', traits: ['concentrate', 'divine', 'manipulate'] },
  { slug: 'manifest-soulforged-armament', name: 'Manifest Soulforged Armament', actionType: 'action', cost: 1, category: 'interaction', traits: ['concentrate', 'divine', 'extradimensional'] },
  { slug: 'map-the-area', name: 'Map the Area', actionType: 'passive', cost: null, category: 'interaction', traits: ['concentrate'] },
  { slug: 'marathon-dash', name: 'Marathon Dash', actionType: 'action', cost: 1, category: 'offensive', traits: ['transcendence'] },
  { slug: 'mark-for-death', name: 'Mark for Death', actionType: 'action', cost: 3, category: 'offensive', traits: ['concentrate'] },
  { slug: 'mark-the-center', name: 'Mark the Center', actionType: 'action', cost: 1, category: 'offensive', traits: ['transcendence'] },
  { slug: 'master-strike', name: 'Master Strike', actionType: 'free', cost: null, category: 'offensive', traits: ['incapacitation', 'rogue'] },
  { slug: 'mighty-rage', name: 'Mighty Rage', actionType: 'free', cost: null, category: 'interaction', traits: ['barbarian'] },
  { slug: 'mirror-trickery', name: 'Mirror-Trickery', actionType: 'reaction', cost: null, category: 'defensive', traits: ['concentrate', 'illusion', 'occult', 'visual'] },
  { slug: 'mirrored-wall', name: 'Mirrored Wall', actionType: 'action', cost: 2, category: 'offensive', traits: ['commander', 'tactic', 'visual'] },
  { slug: 'mirrors-reflection', name: 'Mirror\'s Reflection', actionType: 'action', cost: 1, category: 'interaction', traits: ['illusion', 'magical', 'manipulate', 'thaumaturge'] },
  { slug: 'mist-blending', name: 'Mist Blending', actionType: 'reaction', cost: null, category: 'defensive', traits: ['undine'] },
  { slug: 'mobbing-assault', name: 'Mobbing Assault', actionType: 'action', cost: 1, category: 'offensive', traits: ['concentrate'] },
  { slug: 'mount', name: 'Mount', actionType: 'action', cost: 1, category: 'interaction', traits: ['move'] },
  { slug: 'mountaineering-training', name: 'Mountaineering Training', actionType: 'action', cost: 1, category: 'offensive', traits: ['commander', 'tactic'] },
  { slug: 'mutagenic-flashback', name: 'Mutagenic Flashback', actionType: 'free', cost: null, category: 'interaction', traits: ['alchemist', 'manipulate'] },
  { slug: 'my-legend-must-be-told', name: 'My Legend Must Be Told', actionType: 'free', cost: null, category: 'offensive', traits: [] },
  { slug: 'mystic-aegis', name: 'Mystic Aegis', actionType: 'reaction', cost: null, category: null, traits: ['concentrate', 'magical'] },
  { slug: 'mythic-echo', name: 'Mythic Echo', actionType: 'reaction', cost: null, category: 'offensive', traits: [] },
  { slug: 'name-drop', name: 'Name Drop', actionType: 'reaction', cost: null, category: 'interaction', traits: ['auditory', 'fortune'] },
  { slug: 'naval-training', name: 'Naval Training', actionType: 'action', cost: 1, category: 'offensive', traits: ['commander', 'tactic'] },
  { slug: 'no-scar-but-this', name: 'No Scar but This', actionType: 'action', cost: 1, category: 'offensive', traits: ['concentrate', 'healing', 'transcendence', 'vitality'] },
  { slug: 'nudging-whisper', name: 'Nudging Whisper', actionType: 'passive', cost: null, category: 'offensive', traits: ['curse', 'divine', 'emotion', 'mental'] },
  { slug: 'objection', name: 'Objection', actionType: 'reaction', cost: null, category: 'offensive', traits: ['fortune'] },
  { slug: 'offer-story', name: 'Offer Story', actionType: 'action', cost: 1, category: 'offensive', traits: ['auditory', 'concentrate', 'divine', 'linguistic', 'mental'] },
  { slug: 'once-bitten', name: 'Once Bitten', actionType: 'reaction', cost: null, category: 'offensive', traits: [] },
  { slug: 'one-moment-till-glory', name: 'One Moment till Glory', actionType: 'action', cost: 1, category: 'offensive', traits: ['concentrate', 'emotion', 'mental', 'transcendence'] },
  { slug: 'one-shot-one-kill', name: 'One Shot, One Kill', actionType: 'free', cost: null, category: 'offensive', traits: ['gunslinger'] },
  { slug: 'only-you-and-i', name: 'Only You and I', actionType: 'action', cost: 1, category: 'offensive', traits: ['concentrate', 'transcendence'] },
  { slug: 'opportune-riposte', name: 'Opportune Riposte', actionType: 'reaction', cost: null, category: 'offensive', traits: ['bravado', 'swashbuckler'] },
  { slug: 'opportunistic-accusation', name: 'Opportunistic Accusation', actionType: 'reaction', cost: null, category: 'offensive', traits: ['auditory', 'linguistic', 'mental'] },
  { slug: 'overawe-crowd', name: 'Overawe Crowd', actionType: 'action', cost: 2, category: 'offensive', traits: ['concentrate'] },
  { slug: 'overdrive', name: 'Overdrive', actionType: 'action', cost: 1, category: 'offensive', traits: ['inventor', 'manipulate'] },
  { slug: 'overload-vision', name: 'Overload Vision', actionType: 'reaction', cost: null, category: 'defensive', traits: ['concentrate'] },
  { slug: 'overwhelming-combination', name: 'Overwhelming Combination', actionType: 'action', cost: 1, category: 'offensive', traits: ['flourish'] },
  { slug: 'pacifying-infusion', name: 'Pacifying Infusion', actionType: 'action', cost: 1, category: 'offensive', traits: ['infusion'] },
  { slug: 'palm-an-object', name: 'Palm an Object', actionType: 'action', cost: 1, category: 'interaction', traits: ['manipulate'] },
  { slug: 'passage-of-lines', name: 'Passage of Lines', actionType: 'action', cost: 1, category: 'offensive', traits: ['commander', 'tactic'] },
  { slug: 'patrons-claim', name: 'Patron\'s Claim', actionType: 'action', cost: 2, category: 'offensive', traits: [] },
  { slug: 'patrons-presence', name: 'Patron\'s Presence', actionType: 'action', cost: 2, category: 'offensive', traits: ['aura'] },
  { slug: 'perform', name: 'Perform', actionType: 'action', cost: 1, category: 'interaction', traits: ['concentrate'] },
  { slug: 'pick-a-lock', name: 'Pick a Lock', actionType: 'action', cost: 2, category: 'interaction', traits: ['manipulate'] },
  { slug: 'pincer-attack', name: 'Pincer Attack', actionType: 'action', cost: 1, category: 'offensive', traits: ['commander', 'tactic'] },
  { slug: 'piranha-assault', name: 'Piranha Assault', actionType: 'action', cost: 1, category: 'offensive', traits: ['commander', 'tactic'] },
  { slug: 'pistoleros-retort', name: 'Pistolero\'s Retort', actionType: 'reaction', cost: null, category: 'offensive', traits: ['gunslinger'] },
  { slug: 'pitch-perfect-projection', name: 'Pitch-Perfect Projection', actionType: 'action', cost: 1, category: 'offensive', traits: ['auditory', 'spellshape'] },
  { slug: 'plant-thirty-barbs', name: 'Plant Thirty Barbs', actionType: 'action', cost: 1, category: 'offensive', traits: ['death', 'transcendence'] },
  { slug: 'plummeting-roll', name: 'Plummeting Roll', actionType: 'reaction', cost: null, category: 'defensive', traits: [] },
  { slug: 'point-out', name: 'Point Out', actionType: 'action', cost: 1, category: 'interaction', traits: ['auditory', 'manipulate', 'visual'] },
  { slug: 'pointed-question', name: 'Pointed Question', actionType: 'action', cost: 1, category: 'interaction', traits: ['auditory', 'concentrate', 'investigator', 'linguistic', 'mental'] },
  { slug: 'pop-drop-and-lock', name: 'Pop, Drop, and Lock', actionType: 'action', cost: 2, category: 'offensive', traits: ['brandish', 'commander', 'tactic'] },
  { slug: 'practical-research', name: 'Practical Research', actionType: 'passive', cost: null, category: 'interaction', traits: ['downtime'] },
  { slug: 'primal-howl', name: 'Primal Howl', actionType: 'action', cost: 2, category: 'offensive', traits: ['primal', 'sonic'] },
  { slug: 'primal-roar', name: 'Primal Roar', actionType: 'action', cost: 2, category: 'offensive', traits: ['auditory', 'eidolon'] },
  { slug: 'prophecys-pawn', name: 'Prophecy\'s Pawn', actionType: 'free', cost: null, category: 'interaction', traits: ['divine', 'fortune'] },
  { slug: 'protective-screen', name: 'Protective Screen', actionType: 'action', cost: 1, category: 'offensive', traits: ['brandish', 'commander', 'tactic'] },
  { slug: 'prove-peace', name: 'Prove Peace', actionType: 'action', cost: 2, category: 'interaction', traits: ['concentrate', 'manipulate'] },
  { slug: 'psychic-defense', name: 'Psychic Defense', actionType: 'reaction', cost: null, category: 'defensive', traits: ['concentrate', 'magical'] },
  { slug: 'psychometric-assessment', name: 'Psychometric Assessment', actionType: 'passive', cost: null, category: 'interaction', traits: ['concentrate', 'emotion', 'exploration', 'mental', 'occult'] },
  { slug: 'pursue-a-lead', name: 'Pursue a Lead', actionType: 'passive', cost: null, category: 'interaction', traits: ['concentrate', 'exploration', 'investigator'] },
  { slug: 'quick-alchemy', name: 'Quick Alchemy', actionType: 'action', cost: 1, category: 'interaction', traits: ['alchemist', 'manipulate'] },
  { slug: 'quick-tempered', name: 'Quick-Tempered', actionType: 'free', cost: null, category: 'offensive', traits: ['barbarian'] },
  { slug: 'quick-tincture', name: 'Quick Tincture', actionType: 'action', cost: 1, category: 'interaction', traits: ['investigator', 'manipulate'] },
  { slug: 'race-the-skies', name: 'Race the Skies', actionType: 'action', cost: 1, category: 'offensive', traits: ['concentrate', 'transcendence'] },
  { slug: 'raconteurs-reload', name: 'Raconteur\'s Reload', actionType: 'action', cost: 1, category: 'offensive', traits: ['gunslinger'] },
  { slug: 'rage', name: 'Rage', actionType: 'action', cost: 1, category: 'offensive', traits: ['barbarian', 'concentrate', 'emotion', 'mental'] },
  { slug: 'raise-a-shield', name: 'Raise a Shield', actionType: 'action', cost: 1, category: 'defensive', traits: [] },
  { slug: 'raise-neck', name: 'Raise Neck', actionType: 'action', cost: 1, category: 'offensive', traits: [] },
  { slug: 'raise-slabs', name: 'Raise Slabs', actionType: 'action', cost: 2, category: 'offensive', traits: ['divine', 'earth'] },
  { slug: 'raise-the-horde', name: 'Raise the Horde', actionType: 'action', cost: 2, category: 'offensive', traits: ['concentrate', 'magical', 'manipulate'] },
  { slug: 'raise-the-walls', name: 'Raise the Walls', actionType: 'action', cost: 1, category: 'offensive', traits: ['force', 'transcendence'] },
  { slug: 'rally', name: 'Rally', actionType: 'passive', cost: null, category: 'interaction', traits: ['auditory', 'emotion', 'exploration', 'linguistic', 'mental'] },
  { slug: 'rampaging-ferocity', name: 'Rampaging Ferocity', actionType: 'free', cost: null, category: 'offensive', traits: [] },
  { slug: 'reactive-falsehood', name: 'Reactive Falsehood', actionType: 'reaction', cost: null, category: 'offensive', traits: ['fortune'] },
  { slug: 'reactive-strike', name: 'Reactive Strike', actionType: 'reaction', cost: null, category: 'defensive', traits: [] },
  { slug: 'ready', name: 'Ready', actionType: 'action', cost: 2, category: 'interaction', traits: ['concentrate'] },
  { slug: 'ready-aim-fire', name: 'Ready, Aim, Fire!', actionType: 'action', cost: 2, category: 'offensive', traits: ['brandish', 'commander', 'tactic'] },
  { slug: 'reap-the-field', name: 'Reap the Field', actionType: 'action', cost: 1, category: 'offensive', traits: ['transcendence'] },
  { slug: 'rearrange-bones', name: 'Rearrange Bones', actionType: 'action', cost: 1, category: 'offensive', traits: ['manipulate'] },
  { slug: 'recall-ammunition', name: 'Recall Ammunition', actionType: 'reaction', cost: null, category: 'interaction', traits: ['magical', 'spellshot', 'teleportation'] },
  { slug: 'recall-knowledge', name: 'Recall Knowledge', actionType: 'action', cost: 1, category: 'interaction', traits: ['concentrate', 'secret'] },
  { slug: 'recall-the-teachings', name: 'Recall the Teachings', actionType: 'action', cost: 1, category: 'defensive', traits: ['occult', 'psyche', 'psychic'] },
  { slug: 'recall-under-pressure', name: 'Recall Under Pressure', actionType: 'free', cost: null, category: 'offensive', traits: ['fortune'] },
  { slug: 'recenter', name: 'Recenter', actionType: 'action', cost: 1, category: 'offensive', traits: ['concentrate'] },
  { slug: 'reclaim-destiny', name: 'Reclaim Destiny', actionType: 'free', cost: null, category: 'interaction', traits: ['occult'] },
  { slug: 'reconnoiter', name: 'Reconnoiter', actionType: 'passive', cost: null, category: 'interaction', traits: ['concentrate'] },
  { slug: 'redistribute', name: 'Redistribute', actionType: 'reaction', cost: null, category: 'defensive', traits: ['eidolon'] },
  { slug: 'refocus', name: 'Refocus', actionType: 'passive', cost: null, category: 'interaction', traits: ['concentrate', 'exploration'] },
  { slug: 'rejoin-in-flight', name: 'Rejoin in Flight', actionType: 'action', cost: 2, category: 'offensive', traits: ['transcendence'] },
  { slug: 'release', name: 'Release', actionType: 'free', cost: null, category: 'interaction', traits: ['manipulate'] },
  { slug: 'reload', name: 'Reload!', actionType: 'action', cost: 1, category: 'offensive', traits: ['commander', 'tactic'] },
  { slug: 'reloading-strike', name: 'Reloading Strike', actionType: 'action', cost: 1, category: 'offensive', traits: ['gunslinger'] },
  { slug: 'remove-head', name: 'Remove Head', actionType: 'action', cost: 1, category: 'interaction', traits: ['manipulate'] },
  { slug: 'repair', name: 'Repair', actionType: 'passive', cost: null, category: 'interaction', traits: ['exploration', 'manipulate'] },
  { slug: 'repeat-a-spell', name: 'Repeat a Spell', actionType: 'passive', cost: null, category: 'interaction', traits: ['concentrate', 'exploration'] },
  { slug: 'repel-ambient-magic', name: 'Repel Ambient Magic', actionType: 'action', cost: 1, category: 'defensive', traits: ['concentrate'] },
  { slug: 'reposition', name: 'Reposition', actionType: 'action', cost: 1, category: 'offensive', traits: ['attack'] },
  { slug: 'request', name: 'Request', actionType: 'action', cost: 1, category: 'interaction', traits: ['auditory', 'concentrate', 'linguistic', 'mental'] },
  { slug: 'research', name: 'Research', actionType: 'passive', cost: null, category: 'interaction', traits: ['concentrate', 'exploration'] },
  { slug: 'resist-elf-magic', name: 'Resist Elf Magic', actionType: 'reaction', cost: null, category: 'defensive', traits: [] },
  { slug: 'resist-magic', name: 'Resist Magic', actionType: 'reaction', cost: null, category: 'defensive', traits: [] },
  { slug: 'restorative-teleportation', name: 'Restorative Teleportation', actionType: 'reaction', cost: null, category: 'offensive', traits: ['healing'] },
  { slug: 'restore-the-mind', name: 'Restore the Mind', actionType: 'action', cost: 1, category: null, traits: ['emotion', 'healing', 'mental', 'psyche', 'psychic'] },
  { slug: 'restore-the-moment', name: 'Restore the Moment', actionType: 'reaction', cost: null, category: 'defensive', traits: ['mythic', 'occult'] },
  { slug: 'retraining', name: 'Retraining', actionType: 'passive', cost: null, category: 'interaction', traits: ['downtime'] },
  { slug: 'retributive-strike', name: 'Retributive Strike', actionType: 'reaction', cost: null, category: 'offensive', traits: ['champion', 'divine'] },
  { slug: 'rewrite-fate', name: 'Rewrite Fate', actionType: 'free', cost: null, category: 'interaction', traits: ['fortune', 'mythic'] },
  { slug: 'ring-bell', name: 'Ring Bell', actionType: 'reaction', cost: null, category: 'defensive', traits: ['auditory', 'magical', 'manipulate', 'sonic', 'thaumaturge'] },
  { slug: 'ringing-challenge', name: 'Ringing Challenge', actionType: 'action', cost: 2, category: 'offensive', traits: ['sonic', 'spirit', 'transcendence'] },
  { slug: 'roaring-charge', name: 'Roaring Charge', actionType: 'action', cost: 2, category: 'offensive', traits: ['commander', 'tactic'] },
  { slug: 'royal-grace', name: 'Royal Grace', actionType: 'passive', cost: null, category: 'interaction', traits: ['concentrate', 'exploration', 'linguistic', 'mental'] },
  { slug: 'run-over', name: 'Run Over', actionType: 'action', cost: 3, category: 'offensive', traits: ['move'] },
  { slug: 'runelords-response', name: 'Runelord\'s Response', actionType: 'reaction', cost: null, category: 'defensive', traits: ['arcane', 'concentrate'] },
  { slug: 'salt-wound', name: 'Salt Wound', actionType: 'reaction', cost: null, category: 'offensive', traits: ['undine'] },
  { slug: 'sanguine-revitalization', name: 'Sanguine Revitalization', actionType: 'action', cost: 2, category: 'offensive', traits: ['commander', 'tactic'] },
  { slug: 'scout', name: 'Scout', actionType: 'passive', cost: null, category: 'interaction', traits: ['concentrate', 'exploration'] },
  { slug: 'scout-location', name: 'Scout Location', actionType: 'passive', cost: null, category: 'interaction', traits: ['downtime', 'secret'] },
  { slug: 'search', name: 'Search', actionType: 'passive', cost: null, category: 'interaction', traits: ['concentrate', 'exploration'] },
  { slug: 'secure-disguises', name: 'Secure Disguises', actionType: 'passive', cost: null, category: 'interaction', traits: ['downtime'] },
  { slug: 'seek', name: 'Seek', actionType: 'action', cost: 1, category: 'interaction', traits: ['concentrate', 'secret'] },
  { slug: 'seething-frenzy', name: 'Seething Frenzy', actionType: 'action', cost: 1, category: 'defensive', traits: ['concentrate', 'eidolon', 'emotion', 'mental'] },
  { slug: 'selfish-shield', name: 'Selfish Shield', actionType: 'reaction', cost: null, category: 'defensive', traits: ['champion', 'divine'] },
  { slug: 'sense-direction', name: 'Sense Direction', actionType: 'passive', cost: null, category: 'interaction', traits: ['exploration', 'secret'] },
  { slug: 'sense-motive', name: 'Sense Motive', actionType: 'action', cost: 1, category: 'interaction', traits: ['concentrate', 'secret'] },
  { slug: 'sense-weakness', name: 'Sense Weakness', actionType: 'reaction', cost: null, category: 'interaction', traits: [] },
  { slug: 'set-explosives', name: 'Set Explosives', actionType: 'action', cost: 2, category: 'offensive', traits: ['concentrate'] },
  { slug: 'set-free', name: 'Set Free', actionType: 'reaction', cost: null, category: 'defensive', traits: ['fortune'] },
  { slug: 'settle-emotions', name: 'Settle Emotions', actionType: 'passive', cost: null, category: 'interaction', traits: ['concentrate', 'emotion', 'mental'] },
  { slug: 'sever-conduit', name: 'Sever Conduit', actionType: 'reaction', cost: null, category: 'defensive', traits: ['concentrate'] },
  { slug: 'sever-four-dragonfly-wings', name: 'Sever Four Dragonfly Wings', actionType: 'action', cost: 3, category: 'offensive', traits: ['transcendence'] },
  { slug: 'shadow-step', name: 'Shadow Step', actionType: 'action', cost: 1, category: 'interaction', traits: ['shadow', 'teleportation'] },
  { slug: 'shake-it-off', name: 'Shake It Off', actionType: 'reaction', cost: null, category: 'offensive', traits: ['fortune', 'primal'] },
  { slug: 'share-deaths-promises', name: 'Share Death\'s Promises', actionType: 'free', cost: null, category: 'offensive', traits: [] },
  { slug: 'share-life', name: 'Share Life', actionType: 'reaction', cost: null, category: 'interaction', traits: [] },
  { slug: 'share-senses', name: 'Share Senses', actionType: 'action', cost: 1, category: 'interaction', traits: ['concentrate', 'scrying', 'summoner'] },
  { slug: 'shatter-glass', name: 'Shatter Glass', actionType: 'reaction', cost: null, category: 'offensive', traits: [] },
  { slug: 'shed-spirit', name: 'Shed Spirit', actionType: 'action', cost: 2, category: 'offensive', traits: [] },
  { slug: 'shed-the-mortal-skin', name: 'Shed the Mortal Skin', actionType: 'action', cost: 1, category: 'offensive', traits: ['healing', 'light', 'transcendence', 'vitality'] },
  { slug: 'shielding-wave', name: 'Shielding Wave', actionType: 'action', cost: 1, category: 'offensive', traits: ['primal', 'water'] },
  { slug: 'shields-up', name: 'Shields Up!', actionType: 'action', cost: 1, category: 'offensive', traits: ['commander', 'tactic'] },
  { slug: 'shift-immanence', name: 'Shift Immanence', actionType: 'action', cost: 1, category: 'offensive', traits: ['divine', 'exemplar'] },
  { slug: 'shove', name: 'Shove', actionType: 'action', cost: 1, category: 'offensive', traits: ['attack'] },
  { slug: 'sickening-assault', name: 'Sickening Assault', actionType: 'free', cost: null, category: 'offensive', traits: ['concentrate', 'eidolon'] },
  { slug: 'sidestep-through-time', name: 'Sidestep Through Time', actionType: 'reaction', cost: null, category: 'defensive', traits: ['concentrate', 'occult', 'teleportation'] },
  { slug: 'siegebreaker', name: 'Siegebreaker', actionType: 'action', cost: 2, category: 'offensive', traits: ['gunslinger'] },
  { slug: 'skirt-the-underworld', name: 'Skirt the Underworld', actionType: 'action', cost: 2, category: 'offensive', traits: ['concentrate', 'illusion', 'incapacitation', 'transcendence'] },
  { slug: 'slayers-identification', name: 'Slayer\'s Identification', actionType: 'free', cost: null, category: 'interaction', traits: [] },
  { slug: 'slip-and-sizzle', name: 'Slip and Sizzle', actionType: 'action', cost: 2, category: 'offensive', traits: ['commander', 'tactic'] },
  { slug: 'smoke-blending', name: 'Smoke Blending', actionType: 'reaction', cost: null, category: 'defensive', traits: ['sylph'] },
  { slug: 'sneak', name: 'Sneak', actionType: 'action', cost: 1, category: 'defensive', traits: ['move', 'secret'] },
  { slug: 'soaring-flight', name: 'Soaring Flight', actionType: 'action', cost: 2, category: 'interaction', traits: ['morph', 'primal', 'tengu'] },
  { slug: 'sorshens-devotion', name: 'Sorshen\'s Devotion', actionType: 'action', cost: 2, category: 'offensive', traits: ['arcane', 'concentrate', 'healing'] },
  { slug: 'spasm-of-the-berserker', name: 'Spasm of the Berserker', actionType: 'action', cost: 1, category: 'offensive', traits: ['transcendence'] },
  { slug: 'speed-of-arms', name: 'Speed of Arms', actionType: 'reaction', cost: null, category: 'defensive', traits: ['mythic'] },
  { slug: 'spell-woven-shot', name: 'Spell-Woven Shot', actionType: 'action', cost: 3, category: 'offensive', traits: [] },
  { slug: 'spellsling', name: 'Spellsling', actionType: 'action', cost: 3, category: 'offensive', traits: [] },
  { slug: 'spellstrike', name: 'Spellstrike', actionType: 'action', cost: 2, category: 'offensive', traits: [] },
  { slug: 'spin-tale', name: 'Spin Tale', actionType: 'action', cost: 1, category: 'interaction', traits: ['auditory', 'linguistic'] },
  { slug: 'spinning-crush', name: 'Spinning Crush', actionType: 'action', cost: 3, category: 'offensive', traits: ['gunslinger'] },
  { slug: 'spirit-sanctification', name: 'Spirit Sanctification', actionType: 'action', cost: 1, category: 'interaction', traits: ['concentrate', 'spellshape'] },
  { slug: 'spirits-mercy', name: 'Spirit\'s Mercy', actionType: 'reaction', cost: null, category: 'defensive', traits: [] },
  { slug: 'spiritual-aid', name: 'Spiritual Aid', actionType: 'reaction', cost: null, category: 'offensive', traits: [] },
  { slug: 'spit-ambient-magic', name: 'Spit Ambient Magic', actionType: 'action', cost: 1, category: 'offensive', traits: ['concentrate', 'magical'] },
  { slug: 'spread-propaganda', name: 'Spread Propaganda', actionType: 'passive', cost: null, category: 'interaction', traits: ['exploration', 'secret'] },
  { slug: 'spread-realm', name: 'Spread Realm', actionType: 'free', cost: null, category: 'interaction', traits: ['concentrate'] },
  { slug: 'spring-the-trap', name: 'Spring the Trap', actionType: 'free', cost: null, category: 'interaction', traits: ['gunslinger'] },
  { slug: 'squeeze', name: 'Squeeze', actionType: 'passive', cost: null, category: 'interaction', traits: ['exploration', 'move'] },
  { slug: 'stand', name: 'Stand', actionType: 'action', cost: 1, category: 'interaction', traits: ['move'] },
  { slug: 'starlit-transformation', name: 'Starlit Transformation', actionType: 'action', cost: 1, category: 'interaction', traits: ['arcane'] },
  { slug: 'steal', name: 'Steal', actionType: 'action', cost: 1, category: 'interaction', traits: ['manipulate'] },
  { slug: 'steel-your-resolve', name: 'Steel Your Resolve', actionType: 'action', cost: 1, category: 'offensive', traits: [] },
  { slug: 'stellar-misfortune', name: 'Stellar Misfortune', actionType: 'free', cost: null, category: 'interaction', traits: ['misfortune', 'occult'] },
  { slug: 'step', name: 'Step', actionType: 'action', cost: 1, category: 'interaction', traits: ['move'] },
  { slug: 'stitching-strike', name: 'Stitching Strike', actionType: 'action', cost: 2, category: 'offensive', traits: [] },
  { slug: 'stonestrike-stance', name: 'Stonestrike Stance', actionType: 'action', cost: 1, category: 'offensive', traits: [] },
  { slug: 'stop', name: 'Stop', actionType: 'action', cost: 1, category: 'interaction', traits: ['manipulate'] },
  { slug: 'stride', name: 'Stride', actionType: 'action', cost: 1, category: 'interaction', traits: ['move'] },
  { slug: 'stridulating-song', name: 'Stridulating Song', actionType: 'action', cost: 2, category: 'offensive', traits: ['auditory', 'magical'] },
  { slug: 'strike', name: 'Strike', actionType: 'action', cost: 1, category: 'offensive', traits: ['attack'] },
  { slug: 'strike-breathe-rend', name: 'Strike, Breathe, Rend', actionType: 'action', cost: 1, category: 'offensive', traits: ['spirit', 'transcendence'] },
  { slug: 'strike-hard', name: 'Strike Hard!', actionType: 'action', cost: 2, category: 'offensive', traits: ['brandish', 'commander', 'tactic'] },
  { slug: 'study', name: 'Study', actionType: 'passive', cost: null, category: 'interaction', traits: ['downtime'] },
  { slug: 'stupefying-raid', name: 'Stupefying Raid', actionType: 'action', cost: 2, category: 'offensive', traits: ['commander', 'tactic'] },
  { slug: 'subsist', name: 'Subsist', actionType: 'passive', cost: null, category: 'interaction', traits: ['downtime'] },
  { slug: 'summon-sloth', name: 'Summon Sloth', actionType: 'action', cost: 2, category: 'offensive', traits: ['arcane', 'concentrate'] },
  { slug: 'survive-the-wilds', name: 'Survive the Wilds', actionType: 'action', cost: 1, category: 'offensive', traits: ['aura', 'manipulate', 'transcendence'] },
  { slug: 'sustain', name: 'Sustain', actionType: 'action', cost: 1, category: 'interaction', traits: ['concentrate'] },
  { slug: 'sustain-an-effect', name: 'Sustain an Effect', actionType: 'passive', cost: null, category: 'interaction', traits: ['concentrate', 'exploration'] },
  { slug: 'swarm-forth', name: 'Swarm Forth', actionType: 'action', cost: 2, category: 'offensive', traits: ['concentrate'] },
  { slug: 'swarming-assault', name: 'Swarming Assault', actionType: 'action', cost: 2, category: 'offensive', traits: ['eidolon'] },
  { slug: 'swift-choreography', name: 'Swift Choreography', actionType: 'reaction', cost: null, category: 'offensive', traits: ['auditory', 'linguistic'] },
  { slug: 'swim', name: 'Swim', actionType: 'action', cost: 1, category: 'interaction', traits: ['move'] },
  { slug: 'swirl-crimson-shroud', name: 'Swirl Crimson Shroud', actionType: 'action', cost: 1, category: 'defensive', traits: ['manipulate'] },
  { slug: 'tactical-retreat', name: 'Tactical Retreat', actionType: 'reaction', cost: null, category: 'defensive', traits: ['emotion', 'fear', 'mental'] },
  { slug: 'tactical-takedown', name: 'Tactical Takedown', actionType: 'action', cost: 2, category: 'offensive', traits: ['commander', 'tactic'] },
  { slug: 'tail-toxin', name: 'Tail Toxin', actionType: 'action', cost: 1, category: 'interaction', traits: ['kobold', 'poison'] },
  { slug: 'take-a-breather', name: 'Take a Breather', actionType: 'passive', cost: null, category: 'interaction', traits: ['exploration', 'stamina'] },
  { slug: 'take-control', name: 'Take Control', actionType: 'action', cost: 1, category: 'interaction', traits: ['manipulate'] },
  { slug: 'take-cover', name: 'Take Cover', actionType: 'action', cost: 1, category: 'interaction', traits: [] },
  { slug: 'take-the-high-ground', name: 'Take the High Ground', actionType: 'action', cost: 1, category: 'offensive', traits: ['commander', 'tactic'] },
  { slug: 'talon-stance', name: 'Talon Stance', actionType: 'action', cost: 1, category: 'offensive', traits: ['stance'] },
  { slug: 'tangle-in-riddle', name: 'Tangle in Riddle', actionType: 'action', cost: 1, category: 'offensive', traits: ['auditory', 'mental', 'transcendence'] },
  { slug: 'tap-ley-line', name: 'Tap Ley Line', actionType: 'action', cost: 1, category: 'interaction', traits: ['concentrate'] },
  { slug: 'tap-the-past', name: 'Tap the Past', actionType: 'free', cost: null, category: 'interaction', traits: ['fortune'] },
  { slug: 'taunt', name: 'Taunt', actionType: 'action', cost: 1, category: 'offensive', traits: ['concentrate', 'guardian'] },
  { slug: 'tell-me-more', name: 'Tell Me More', actionType: 'action', cost: 2, category: 'interaction', traits: [] },
  { slug: 'ten-paces', name: 'Ten Paces', actionType: 'free', cost: null, category: 'offensive', traits: ['gunslinger'] },
  { slug: 'tenacious-stance', name: 'Tenacious Stance', actionType: 'action', cost: 1, category: 'defensive', traits: ['stance'] },
  { slug: 'tendril-strike', name: 'Tendril Strike', actionType: 'action', cost: 1, category: 'offensive', traits: ['eidolon'] },
  { slug: 'thats-my-number', name: 'That\'s My Number', actionType: 'reaction', cost: null, category: 'interaction', traits: ['fortune'] },
  { slug: 'the-bigger-they-are', name: 'The Bigger They Are', actionType: 'action', cost: 1, category: 'offensive', traits: ['brandish', 'commander', 'tactic'] },
  { slug: 'thermal-eruption', name: 'Thermal Eruption', actionType: 'action', cost: 2, category: 'offensive', traits: ['fire', 'primal'] },
  { slug: 'thoughtful-reload', name: 'Thoughtful Reload', actionType: 'action', cost: 1, category: 'interaction', traits: ['gunslinger'] },
  { slug: 'threatening-approach', name: 'Threatening Approach', actionType: 'action', cost: 2, category: 'offensive', traits: [] },
  { slug: 'thundering-roar', name: 'Thundering Roar', actionType: 'action', cost: 1, category: 'offensive', traits: ['auditory', 'concentrate', 'emotion', 'fear', 'flourish', 'mental', 'sonic'] },
  { slug: 'timely-dodge', name: 'Timely Dodge', actionType: 'reaction', cost: null, category: 'defensive', traits: [] },
  { slug: 'topple-the-pillar-of-heaven', name: 'Topple the Pillar of Heaven', actionType: 'action', cost: 2, category: 'offensive', traits: ['transcendence'] },
  { slug: 'touch-and-go', name: 'Touch and Go', actionType: 'action', cost: 1, category: 'interaction', traits: ['gunslinger'] },
  { slug: 'toxic-skin', name: 'Toxic Skin', actionType: 'reaction', cost: null, category: 'defensive', traits: ['grippli', 'poison'] },
  { slug: 'toxic-touch', name: 'Toxic Touch', actionType: 'action', cost: 1, category: 'offensive', traits: ['poison'] },
  { slug: 'track', name: 'Track', actionType: 'passive', cost: null, category: 'interaction', traits: ['concentrate', 'exploration', 'move'] },
  { slug: 'transform-ammunition', name: 'Transform Ammunition', actionType: 'free', cost: null, category: 'offensive', traits: ['magical'] },
  { slug: 'travel', name: 'Travel', actionType: 'passive', cost: null, category: 'interaction', traits: ['move'] },
  { slug: 'treat-disease', name: 'Treat Disease', actionType: 'passive', cost: null, category: 'interaction', traits: ['downtime', 'manipulate'] },
  { slug: 'treat-poison', name: 'Treat Poison', actionType: 'action', cost: 1, category: 'interaction', traits: ['manipulate'] },
  { slug: 'treat-wounds', name: 'Treat Wounds', actionType: 'passive', cost: null, category: 'interaction', traits: ['exploration', 'healing', 'manipulate'] },
  { slug: 'trench-digging', name: 'Trench Digging', actionType: 'reaction', cost: null, category: 'defensive', traits: [] },
  { slug: 'trip', name: 'Trip', actionType: 'action', cost: 1, category: 'offensive', traits: ['attack'] },
  { slug: 'true-shapeshift', name: 'True Shapeshift', actionType: 'action', cost: 2, category: 'offensive', traits: ['concentrate'] },
  { slug: 'tumble-through', name: 'Tumble Through', actionType: 'action', cost: 1, category: 'interaction', traits: ['move'] },
  { slug: 'turn-aside-ambient-magic', name: 'Turn Aside Ambient Magic', actionType: 'action', cost: 1, category: 'defensive', traits: ['concentrate'] },
  { slug: 'ultimatum-of-liberation', name: 'Ultimatum of Liberation', actionType: 'action', cost: 1, category: 'interaction', traits: ['auditory', 'linguistic', 'mental', 'mythic'] },
  { slug: 'unleash-psyche', name: 'Unleash Psyche', actionType: 'free', cost: null, category: 'defensive', traits: ['psychic'] },
  { slug: 'unleash-realm', name: 'Unleash Realm', actionType: 'free', cost: null, category: 'offensive', traits: ['concentrate'] },
  { slug: 'unravel-the-future', name: 'Unravel the Future', actionType: 'action', cost: 1, category: 'offensive', traits: ['fortune', 'transcendence'] },
  { slug: 'unwavering-resilience', name: 'Unwavering Resilience', actionType: 'reaction', cost: null, category: 'offensive', traits: [] },
  { slug: 'upstage', name: 'Upstage', actionType: 'reaction', cost: null, category: 'defensive', traits: [] },
  { slug: 'valkyries-charge', name: 'Valkyrie\'s Charge', actionType: 'action', cost: 3, category: 'offensive', traits: ['brandish', 'commander', 'tactic'] },
  { slug: 'venom-draw', name: 'Venom Draw', actionType: 'action', cost: 1, category: 'offensive', traits: [] },
  { slug: 'verdant-rest', name: 'Verdant Rest', actionType: 'action', cost: 1, category: 'offensive', traits: ['concentrate'] },
  { slug: 'visions-of-sin', name: 'Visions of Sin', actionType: 'action', cost: 2, category: 'offensive', traits: ['divine', 'eidolon', 'emotion', 'mental'] },
  { slug: 'vital-shot', name: 'Vital Shot', actionType: 'action', cost: 2, category: 'offensive', traits: ['gunslinger'] },
  { slug: 'warding-sign', name: 'Warding Sign', actionType: 'reaction', cost: null, category: 'defensive', traits: ['concentrate'] },
  { slug: 'water-transfer', name: 'Water Transfer', actionType: 'action', cost: 2, category: 'offensive', traits: ['primal', 'teleportation', 'water'] },
  { slug: 'weaponsight', name: 'Weaponsight', actionType: 'action', cost: 1, category: 'offensive', traits: ['concentrate', 'magical'] },
  { slug: 'whirlwind-maul', name: 'Whirlwind Maul', actionType: 'action', cost: 2, category: 'offensive', traits: ['eidolon'] },
  { slug: 'wicked-thorns', name: 'Wicked Thorns', actionType: 'reaction', cost: null, category: 'offensive', traits: [] },
  { slug: 'wind-them-up', name: 'Wind Them Up', actionType: 'action', cost: 2, category: 'offensive', traits: ['gunslinger'] },
  { slug: 'winged-leap', name: 'Winged Leap', actionType: 'action', cost: 1, category: 'offensive', traits: [] },
  { slug: 'wish-for-luck', name: 'Wish for Luck', actionType: 'free', cost: null, category: 'interaction', traits: ['arcane', 'auditory', 'fortune'] },
  { slug: 'wyrms-breath', name: 'Wyrm\'s Breath', actionType: 'free', cost: null, category: 'offensive', traits: ['concentrate', 'eidolon'] },
]

/** Complete action lookup map. Entries with combat outcomes have `outcomes` attached from ACTION_OUTCOMES. */
export const ACTIONS: ReadonlyMap<string, Action> = new Map(
  RAW_ACTIONS.map(raw => [
    raw.slug,
    { ...raw, ...(ACTION_OUTCOMES[raw.slug] ? { outcomes: ACTION_OUTCOMES[raw.slug] } : {}) },
  ])
)
